package model.tournament;

public enum KOOriginType {
	PREQUALIFIED,
	PREVIOUS_GROUP_STAGE,
	PREVIOUS_KNOCKOUT_ROUND,
	PREVIOUS_LEAGUE,
	PREVIOUS_QUALIFICATION_GROUP_STAGE,
	PREVIOUS_QUALIFICATION_KNOCKOUT_ROUND,
	OTHER_COMPETITION;
}
